import { expect, test } from "vitest";
import * as HeadlessUI from "../src/index.ts";

const expectedRuntimeExports = [
  "Button",
  "Checkbox",
  "CloseButton",
  "Combobox",
  "ComboboxButton",
  "ComboboxInput",
  "ComboboxLabel",
  "ComboboxOption",
  "ComboboxOptions",
  "DataInteractive",
  "Description",
  "Dialog",
  "DialogBackdrop",
  "DialogDescription",
  "DialogPanel",
  "DialogTitle",
  "Disclosure",
  "DisclosureButton",
  "DisclosurePanel",
  "Field",
  "Fieldset",
  "FocusTrap",
  "FocusTrapFeatures",
  "Input",
  "Label",
  "Legend",
  "Listbox",
  "ListboxButton",
  "ListboxLabel",
  "ListboxOption",
  "ListboxOptions",
  "ListboxSelectedOption",
  "Menu",
  "MenuButton",
  "MenuHeading",
  "MenuItem",
  "MenuItems",
  "MenuSection",
  "MenuSeparator",
  "Popover",
  "PopoverBackdrop",
  "PopoverButton",
  "PopoverGroup",
  "PopoverOverlay",
  "PopoverPanel",
  "Portal",
  "Radio",
  "RadioGroup",
  "RadioGroupDescription",
  "RadioGroupLabel",
  "RadioGroupOption",
  "Select",
  "Switch",
  "SwitchDescription",
  "SwitchGroup",
  "SwitchLabel",
  "Tab",
  "TabGroup",
  "TabList",
  "TabPanel",
  "TabPanels",
  "Textarea",
  "Transition",
  "TransitionChild",
  "useClose",
] as const;

test("the public package exposes exactly the audited 2.2.10 runtime surface", () => {
  expect(Object.keys(HeadlessUI).sort((a, z) => a.localeCompare(z))).toEqual(
    [...expectedRuntimeExports].sort((a, z) => a.localeCompare(z)),
  );
  expect(expectedRuntimeExports).toHaveLength(65);
});
